name: CI

permissions:
  contents: read
  actions: read
  id-token: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.0"
      - name: Install project
        run: pip install --group dev --group test -e .
      - name: run pre-commit
        run: "pre-commit run --all"
  ci-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14.0-beta.2"]
        pylint-version: ["3.3.*", "3.*"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: pip install --group test -e .
      - name: "Install pylint"
        run: "pip install -U pylint==${{ matrix.pylint-version }}"
      - name: run tests (with coverage)
        run: "pytest --cov --cov-report xml --cov-config pyproject.toml test/"
      - name: run diff-cover
        run: "diff-cover --config-file pyproject.toml coverage.xml"
